### ISSUE TITLE
Logarithmic Value Axes

### ISSUE THREAD

**Issue by Kvaz1r** [wxIshiko/wxCharts#19]
Sometimes need plot graphic with different value axis, so will be good have such possibility for wxmath2dplot. Most popular is logarithmic.  But I think that would be better instead implementation set of standard forms - add methods:
SetXAxesValue(std::function<double> &op);
SetYAxesValue(std::function<double> &op);
or something like that.

**Comment by xleclercq** [comment]
I agree. This is why there is already a enum wxChartAxisType. It can be extended to add logarithmic scale and also custom values.
We can provide a set of popular options (dates, logarithmic for instance).
And also what you suggest:
SetXAxesValue(std::function &op);
SetYAxesValue(std::function &op);

**Comment by Kvaz1r** [comment]
Yes, your variant seems best solution.

**Comment by Kvaz1r** [comment]
Since now this features there is in example, I close the issue.
