### ISSUE TITLE
Can't compile wxcharts_vc16.vcxproj with VS2019 (vc142)

### ISSUE THREAD

**Issue by Anton-V-K** [wxIshiko/wxCharts#194]
When compiling `wxcharts_vc16.vcxproj` (main branch) with VS2019 (vc142) following errors occur for each CPP-file:
`wxWidgets-3.1.5\include\msvc\wx\setup.h(140,10): fatal error C1083: Cannot open include file: '../../../lib/vc_x64_lib/mswud/wx/setup.h': No such file or directory (compiling source file ..\..\src\wxchartsdataset.cpp)`
The correct dir name is `vc14x_x64_dll` and not `vc_x64_lib`, so probably somethings is wrong with pre-processor defines in `wxcharts_vc16.vcxproj` (missing `wxMSVC_VERSION_AUTO`?)

VS2019 16.11.2
wxWidgets 3.1.5
OS: Windows 10 21H1 64-bit

**Comment by xleclercq** [comment]
Did you build wxWidgets as a shared lib or static libs? The folder on my computer is vc_x64_lib.

**Comment by xleclercq** [comment]
Lines 28 and 29 here https://github.com/wxIshiko/wxCharts/blob/main/build/bakefiles/wxcharts.bkl#L28 I think are the only places where we configure the wxWidgets installation.

**Comment by xleclercq** [comment]
Looking at include\msvc\wx\setup.h there are a series of MACROs that define where it looks for lib/vc_x64_lib/mswud/wx/setup.h or equivalent such as WXUSINGDLL.

**Comment by Anton-V-K** [comment]
> Did you build wxWidgets as a shared lib or static libs?

I haven't built it by myself.
I've downloaded the headers along with the pre-built binaries from the official site.

**Comment by xleclercq** [comment]
Did you try defining WXUSINGDLL in your project's compile options and see if it looks in the right location?

**Comment by xleclercq** [comment]
Can you give me a link to the page where you downloaded it from?

**Comment by Anton-V-K** [comment]
For my project I define `_WINDOWS;WIN32;__WXMSW__;wxMSVC_VERSION_AUTO;wxUSE_UNICODE;WXUSINGDLL;...`. It has no problems with picking up the proper `setup.h`.

The official page for downloading wxWidgets library is https://www.wxwidgets.org/downloads/.
I use Latest Development Release 3.1.5 for VS 2015/2017/2019.

**Comment by xleclercq** [comment]
Build instructions have now been provided at: https://github.com/wxIshiko/wxCharts/tree/main/docs/installation.
We use CMake so we rely on that to configure wxWidgets correctly.
