### ISSUE TITLE
new chart types

### ISSUE THREAD

**Issue by mumin16** [wxIshiko/wxCharts#2]
Do you plan to add support for chart types, such as the ohlc, candlestick?

**Comment by xleclercq** [comment]
I had a look at these charts and they don't seem too hard to implement based on the existing charts. I'll have a look at this this weekend.

**Comment by xleclercq** [comment]
I have added wxCandlestickChartCtrl and wxOHLCChartCtrl. See the samples WxOHLC and WxCandlestick. I will now close this issue. Undoubtedly further fixes and enhancements will be needed but please raise new issues for any changes required.
