### ISSUE TITLE
issue while compiling the demo of pie chart

### ISSUE THREAD

**Issue by rodingbao** [wxIshiko/wxCharts#209]
Dear all:

I am trying to compiling the demo of pie chart.  the following messege displayed.

undefined reference to `wxPieChartCtrl::wxPieChartCtrl(wxWindow*, int, wxSharedPtr<wxPieChartData>, wxPoint const&, wxSize const&, long)'

can anyone help or comment?

Best regards
BZG

**Comment by xleclercq** [comment]
Hi, are you building on Windows?
Can you check that the project includes the wxCharts.lib in the link options?

**Comment by rodingbao** [comment]
Yes,I built it in windows,  I put libwxcharts.dll in my demo folder,  wxBarChartCtrl, wxLineChartCtrl and wxColumnChartCtrl worked well.

**Comment by xleclercq** [comment]
Oh I see. Thanks for the clarification. I will have a look tonight.

**Comment by xleclercq** [comment]
I have tried to build the samples with the CMake build files using the following procedure.

mkdir build_cmake
cd build_cmake
cmake -G "Visual Studio 16 2019" -A x64 -DBUILD_SHARED_LIBS=ON -DBUILD_SAMPLES=ON ..
cmake —build .

This successfully built the samples. It puts them in build_cmake/bin.
This is using the most recent main branch.

I will try to build the samples from the IDE (rather than cmake --build .) later this week. However if you can try the procedure above and let me know if it works for you. I didn't spot any obvious difference between the wxPieChartCtrl and other chart classes that would explain why that one doesn't build.

**Comment by rodingbao** [comment]
thank you, xleclercq, I will download the branch and let you know the result.

**Comment by rodingbao** [comment]
Hi, xleclercq, 

I downloaded the newest main branch, and compiled with CMAKE and TDM-GCC 9.2, I got all the demo exe files ,  static library (lib libwxcharts.a)  and dynamic library(libwxcharts.dll.a /  libwxcharts.dll) .

I tested all  demo exe files ,  worked well.

but when I try to complie my test program with the newest library in clion,  issue happend "cannot find -lwxcharts", there was no isssue when I used the original library.  following are the setting in Cmakelist.txt of test program.

include_directories(D:/Coding/lib/wxCharts/include)
include_directories(D:/Coding/lib/wxCharts/lib)
target_link_libraries(test libwxcharts.a)

note: I put  library files under folder D:/Coding/lib/wxCharts/lib

Best regards
BZG

**Comment by xleclercq** [comment]
Did you try running this under a debugger? What does the callstack look like?
Or alternatively, could you give me the complete example so I can compile and execute here?

**Comment by rodingbao** [comment]
I didnt run under a debugger, I attached the completed code as below, 
[test.zip](https://github.com/wxIshiko/wxCharts/files/10986120/test.zip)

it is a function to create 3 charts (column,doughnut and pie) in  bSizer2, bSizer2 is sizer for chart.bSizer1 is the top sizer of dialog.

Fail to compile with message  "Process finished with exit code -1073741511 (0xC0000139)" 

when I delete following code,  compile success and column,doughnut worked well.

       auto* pieChartCtrl = new wxPieChartCtrl(this, wxID_ANY, chartData2);
       bSizer2->Add(pieChartCtrl , 1, wxEXPAND);

<img width="224" alt="image" src="https://user-images.githubusercontent.com/119423811/225495285-04a20a76-7c27-4596-916f-d6cbd1289cfb.png">
