### ISSUE TITLE
how to redefine the color theme of column chart?

### ISSUE THREAD

**Issue by rodingbao** [wxIshiko/wxCharts#213]
dear all:
   
    I want to  replace the defalut color theme of column chart
    here is my code,   it's success to define the wxChartsDatasetTheme, but fail when I update the wxChartsDefaultTheme.  
    can anyone comment or help improving?

    wxVector<double> t_points;
    for (size_t i = 0; i < points.size(); i++) {
      t_points.assign(points[i].begin(), points[i].end());

      wxChartsDatasetTheme *datasettheme = new wxChartsDatasetTheme();
      datasettheme->SetColumnChartDatasetOptions(wxColumnChartDatasetOptions(
          wxChartsPenOptions(wxColour(COLOR[i]), 2),
          wxChartsBrushOptions(wxColour(COLOR[i]))));
      wxChartsDefaultTheme->SetDatasetTheme(
          wxChartsDatasetId::CreateImplicitId(i),
          wxSharedPtr<wxChartsDatasetTheme>(datasettheme));

      wxChartsDoubleDataset::ptr dataset(
          new wxChartsDoubleDataset(seriesName[i], t_points));
      chartData->AddDataset(dataset);
    }

Best regards
BZG

**Comment by Kvaz1r** [comment]
What exactly doesn't work? Your code produce compile error, runtime error, silently doesn't work as expected?

First of all do it outside the loop, like I'd showed in this issue - #165

**Comment by rodingbao** [comment]
compile error,  message as below.

C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../build-Release/family/main.cpp.o:main.cpp:(.rdata$.refptr.wxChartsDefaultTheme[.refptr.wxChartsDefaultTheme]+0x0): undefined reference to `wxChartsDefaultTheme'


发件人: ***@***.***>
发送时间: 2023年8月21日 3:02
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [wxIshiko/wxCharts] how to redefine the color theme of column chart? (Issue #213)


What exactly doesn't work? Your code produce compile error, runtime error, silently doesn't work as expected?

First of all do it outside the loop, like I'd showed in this issue - #165<https://github.com/wxIshiko/wxCharts/issues/165>

―

**Comment by rodingbao** [comment]
when I link with the static lib, the issue fixed. dont know what happend. just close the isuee.
