### ISSUE TITLE
the color of serie in legend are wrong

### ISSUE THREAD

**Issue by rodingbao** [wxIshiko/wxCharts#229]
![image](https://github.com/user-attachments/assets/e3d23cb1-6ae4-4520-b97a-5d6a27588db0)
![image](https://github.com/user-attachments/assets/f9792991-7f16-4fce-b4df-9e15e04b09fb)
![image](https://github.com/user-attachments/assets/c3fc611a-80c8-4d03-9e41-a2cb43848b51)
![image](https://github.com/user-attachments/assets/bdba8c69-02e0-4db2-9605-b8c2133f4ec6)

**Comment by xleclercq** [comment]
I'm currently fixing/improving the build system but will try to have a look at this soon.

**Comment by xleclercq** [comment]
I see you are using a custom color scheme. What method did you use to set the colors on the bar or column chart? Are you changing the wxChartsDefaultTheme or creating another theme entirely?

**Comment by xleclercq** [comment]
Actually, looking at your other bug report (https://github.com/wxIshiko/wxCharts/issues/228) it seems it's working for the line chart but that's weird because I think they use the same inputs. Are you doing anything different between the line chart and bar chart?

**Comment by rodingbao** [comment]
yes, they use the same inputs. no different between the line chart and bar chart.  I changed the wxChartsDefaultTheme. I attahced my code for reference.

  wxChartsDatasetTheme *datasettheme = new wxChartsDatasetTheme();
    if (chartType == B_CHART_VBAR)
      datasettheme->SetColumnChartDatasetOptions(
          wxColumnChartDatasetOptions(wxChartsPenOptions(color, 2), wxChartsBrushOptions(color)));
    else if (chartType == B_CHART_HBAR)
      datasettheme->SetBarChartDatasetOptions(
          wxBarChartDatasetOptions(wxChartsPenOptions(color, 2), wxChartsBrushOptions(color)));
    else if (chartType == B_CHART_VSBAR)
      datasettheme->SetStackedColumnChartDatasetOptions(
          wxStackedColumnChartDatasetOptions(wxChartsPenOptions(color, 2), wxChartsBrushOptions(color)));
    else if (chartType == B_CHART_HSBAR)
      datasettheme->SetStackedBarChartDatasetOptions(
          wxStackedBarChartDatasetOptions(wxChartsPenOptions(color, 2), wxChartsBrushOptions(color)));
    else
      datasettheme->SetLineChartDatasetOptions(wxLineChartDatasetOptions(color, color, wxTransparentColor));
    wxChartsDefaultTheme->SetDatasetTheme(wxChartsDatasetId::CreateImplicitId(i),
                                          wxSharedPtr<wxChartsDatasetTheme>(datasettheme));

**Comment by rodingbao** [comment]
I add following code,  the issue was solved .it seems that the legend used the color from line theme,

```
 wxChartsDefaultTheme->GetDatasetTheme(wxChartsDatasetId::CreateImplicitId(i))
        ->SetLineChartDatasetOptions(wxLineChartDatasetOptions(color, color, color));
```
