### ISSUE TITLE
Create a gitter chat room

### ISSUE THREAD

**Issue by Kvaz1r** [wxIshiko/wxCharts#26]
Sometimes github issue not very well fit to conversation about features project and so on.  Therefore I think would be good add such chat on gitter or other place.

**Comment by xleclercq** [comment]
That's easy enough to do. I didn't know about gitter.im but it looks fine.
I have created a room called wxIshiko/wxCharts and a link to it has been added to the README file.
[![Gitter](https://badges.gitter.im/wxIshiko/wxCharts.svg)](https://gitter.im/wxIshiko/wxCharts?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
