### ISSUE TITLE
Hide additional window on the chart

### ISSUE THREAD

**Issue by Kvaz1r** [wxIshiko/wxCharts#3]
Is there a possibility do not display a message box when you hover over a point on the chart?

**Comment by xleclercq** [comment]
These are called tooltips and it should be possible to disable them. I'm not sure whether the functions to disable them have been added though. I'll have a look this weekend and test this.

**Comment by xleclercq** [comment]
Does this not work?

```
// Create the line chart widget from the constructed data
wxLineChartOptions options;
options.SetShowTooltips(false);
wxLineChartCtrl* lineChartCtrl = new wxLineChartCtrl(panel, wxID_ANY, chartData,
	options, wxDefaultPosition, wxDefaultSize, wxBORDER_NONE);
```

**Comment by Kvaz1r** [comment]
Yes, thank you, it works (I use wxLineChart).

**Comment by helha54** [comment]
I tried the wxLineChartOptions but i always get that there is no SetShowTooltip under optiopns.

'class wxLineChartOptions' has no member named 'SetShowTooltips'

**Comment by Kvaz1r** [comment]
Yes, the library was under active development so now to hide tooltip use:
`options.GetCommonOptions().SetShowTooltips(false);`

**Comment by helha54** [comment]
Thank's for the help that did work fine. Can i also remove the points from the Linechart that i only have the line in the charts witout the points?

**Comment by Kvaz1r** [comment]
> Can i also remove the points from the Linechart that i only have the line in the charts witout the points?

Unfortunately there isn't such option. But you can add it with minimal changes.

Just add parameter to constructor of wxLineChartDatasetOptions (wxlinechartoptions.h and wxlinechartoptions.cpp):
.h file:
```
    wxLineChartDatasetOptions(const wxColor &dotColor, const wxColor &dotStrokeColor,
        const wxColor &fillColor, bool showDots = true);
```
.cpp:
```
wxLineChartDatasetOptions::wxLineChartDatasetOptions(const wxColor& dotColor,
    const wxColor& dotStrokeColor,
    const wxColor& fillColor,
    bool showDots)
    : m_showDots(showDots), m_dotPenOptions(dotStrokeColor, 1), m_dotBrushOptions(dotColor),
...
```

In any case I am going to raise separate issue for it.

**Comment by helha54** [comment]
I updated and compiled my library and the .h file. But I'm not shure how to call it. 

wxChartsDatasetTheme* datasettheme = new wxChartsDatasetTheme();
            datasettheme->SetLineChartDatasetOptions(wxLineChartDatasetOptions(
                        color,
                        color,
                        wxTransparentColor,
                        true
                    ));

is how I tried it. I also set a variable up to hold the value 'true' or 'false' . Maybe You have a hint.

**Comment by helha54** [comment]
I'm sorry. Everything worked fine but I had a second set of the '.h' fieles a modified the wrong one. All Ok now
