### ISSUE TITLE
Save graphics into a file.

### ISSUE THREAD

**Issue by Kvaz1r** [wxIshiko/wxCharts#5]
How save chart into a file?

**Comment by Kvaz1r** [comment]
I moved the code from the function DrawToolTips into new method and save image that way:

```
	   int w,h;
	   lineChartCtrl->GetSize(&w,&h);
	   wxBitmap bmp(w,h);
	   wxMemoryDC mdc(bmp);
	   wxGraphicsContext* gdc = wxGraphicsContext::Create( mdc );
	   lineChartCtrl->Draw(gdc);
	   bmp.ConvertToImage().SaveFile("E:/test2.bmp");
```
but the background image somehow black color.

**Comment by xleclercq** [comment]
I'm not sure but my guess would be that it is due to the fact the controls have the wxBG_STYLE_PAINT flag set.
Try to call mdc.Clear() to draw the background explicitly and maybe you need to set the background color as well.

I haven't given much thought about supporting printing yet.

**Comment by Kvaz1r** [comment]
Yes, you are right. If used method Clear for object of wxMemoryDC then drawing is correct.

**Comment by helha54** [comment]
Can i only save the file by using the right mouse-button or can i save the line-chart by a command

**Comment by Kvaz1r** [comment]
If chart type contains Save method you can call it, which one do you want to use?

**Comment by helha54** [comment]
The charttype contains a save method and Im using wxLinecharts and want to save the chart to use it in an pdf-file

**Comment by Kvaz1r** [comment]
wxWidgets hasn't support for pdf so to work with this format you should use some library. I personally use wxPdfDoc - https://github.com/utelle/wxpdfdoc and I think you can use it to draw any bitmap.

**Comment by helha54** [comment]
Im using wxPdfDoc too, but iI would like to place the saved charts on the pdf, I need a a lot a charts to make a report and believed the best way was to place the saved outputs.(I'm talking about 100 datasets)

**Comment by Kvaz1r** [comment]
If you want save chart in pdf file just do something like that:

```
    int w, h;
    lineChartCtrl->GetSize(&w, &h);
    wxBitmap bmp(w, h);
    wxMemoryDC mdc(bmp);
    mdc.Clear();

    wxPdfDC dc;

    wxGraphicsContext* gc = wxGraphicsContext::Create(mdc);
    if (gc)
    {
        lineChartCtrl->Save(*gc); // draw in memory (bitmap)

        bool ok = dc.StartDoc("");
        if (ok)
        {
            dc.StartPage();
            dc.DrawBitmap(bmp, 0, 0); //draw bitmap on pdf, (0,0) - position
            dc.EndPage();
            dc.EndDoc();
        }

        delete gc;
    }
```

**Comment by helha54** [comment]
Thank You for the help. I had a look into my Report i made with Excel there i have 640 scartplots , 20Linecharts with 32 Datasets and 20 additional Scatterplots. That is a mess to doe with Exel. You also copy everything and it runs for ever.
Now Im redoing it wxSqLite, wxPdfDoc. It's only three different Charts with lots of Data. Thank again for Yout Support.

**Comment by helha54** [comment]
I tried the code You have providit but I alway get the following Error-Message from the compiler:

error: 'class wxLineChartCtrl' has no member named 'Save'; did you mean 'Move'?

I had a look into that class and 'Save' is in there and it is Puplic:

**Comment by Kvaz1r** [comment]
Ah, that's because I use slightly different version of the library than in current master and alpha branches. Just add this:
```
    virtual void Save(wxGraphicsContext &gc)
    {
        GetChart().Draw(gc);
    }
```

to [wxChartCtrl](https://github.com/wxIshiko/wxCharts/blob/dff85f602d8a25c0c3ad8844227597b09fbca920/include/wx/charts/wxchartctrl.h#L37).

**Comment by helha54** [comment]
Do i to put it in wxChartCtrl.h or in wxChartCtrl.cpp or are we talking about wxLineChartctrl.h and wxLineChartctrl.h

**Comment by Kvaz1r** [comment]
wxchartctrl.h

**Comment by helha54** [comment]
Thank You for the support. I made the same to My ScatterPlot and it worked also.
