### ISSUE TITLE
Support iOS

### ISSUE THREAD

**Issue by AAChartModel** [wxIshiko/wxCharts#71]
iOS support c++ hybrid programing, so is it possible that wxCharts support iOS platform?

**Comment by xleclercq** [comment]
wxCharts needs the wxWidgets framework. I think the biggest issue here is the wxWidgets support for iOS. From what I can see on the wxWidgets support for iOS is immature.

**Comment by AAChartModel** [comment]
I see, maybe it is not a good idea.
