### ISSUE TITLE
Setting fixed range for axis doesn't work. 

### ISSUE THREAD

**Issue by Kvaz1r** [wxIshiko/wxCharts#81]
### MCVE

```
#include <wx/app.h>
#include <wx/wx.h>
#include <wx/charts/wxcharts.h>

class WxMath2DFrame : public wxFrame
	{
	public:
		WxMath2DFrame(const wxString& title): wxFrame(NULL, wxID_ANY, title)
			{
			wxMath2DPlotData chartData;
			wxMath2DPlotOptions options;
			options.GetCommonOptions().SetShowTooltips(false);
			options.GetGridOptions().GetXAxisOptions().SetExplicitStartValue(-13);
			options.GetGridOptions().GetXAxisOptions().SetExplicitEndValue(7);
			options.GetGridOptions().GetYAxisOptions().SetExplicitStartValue(-4);
			options.GetGridOptions().GetYAxisOptions().SetExplicitEndValue(9);
			
			wxVector<wxPoint2DDouble> points;
			auto pi = 3.1415926535897;
			for(auto x = -2*pi; x<pi; x+= 0.1)
				points.push_back(wxPoint2DDouble(x,cos(x)*sin(x)));

			wxMath2DPlotDataset::ptr dataset(new wxMath2DPlotDataset(wxColor(250, 20, 20, 0x78),
				wxColor(0, 0, 0, 0xB8),points));
			chartData.AddDataset(dataset);

			auto math2dPlotCtrl = new wxMath2DPlotCtrl(this, wxID_ANY, chartData,options);
			//code below will compile if your apply patch from https://github.com/wxIshiko/wxCharts/pull/79
			//math2dPlotCtrl->SetFixedAxesRange(wxPoint2DDouble(-13,-4),wxPoint2DDouble(7,9));
			wxBoxSizer* topSizer = new wxBoxSizer(wxHORIZONTAL);
			topSizer->Add(math2dPlotCtrl, 1, wxEXPAND);
			SetSizerAndFit(topSizer);
			}
	};

class WxMath2DApp : public wxApp
	{
	public:
		virtual bool OnInit()
			{
			WxMath2DFrame* frame = new WxMath2DFrame("MCVE");
			frame->Show(true);
			return true;
			}
	};

wxIMPLEMENT_APP(WxMath2DApp);
```

**Comment by neworldemancer** [comment]
This method sets the range instead of deriving those from the data points. The actual display range is then calculated by wxChartUtilities::CalculateGridRange, enlarging it to the nearest round values.

**Comment by neworldemancer** [comment]
Unfortunately I'm not very familiar with the development pipeline in this project. 
Where should this be documented? Are there some specific docs, or proper comment in code would suffice?

**Comment by Kvaz1r** [comment]
> Unfortunately I'm not very familiar with the development pipeline in this project.

From my experience nothing special, except that pull request should be small enough so it will easy to review. And there was recently added alpha branch so better re-target PR to it. It's very simple just select from drop-down list under title when clicked on "Edit "near header.  I think @xleclercq just didn't notice your PR so it wasn't reviewed.  And you can ask something specific in [gitter room](https://gitter.im/wxIshiko/wxCharts?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). 

> Where should this be documented? Are there some specific docs, or proper comment in code would suffice?

As for me usual comment above declaration would be enough.
