### ISSUE TITLE
[Feature request] Box plot

### ISSUE THREAD

**Issue by Kvaz1r** [wxIshiko/wxCharts#82]
[Description](https://en.wikipedia.org/wiki/Box_plot)

**Comment by xleclercq** [comment]
It's a candlestick chart with an extra line in the box essentially. This should be easy to do.

**Comment by Kvaz1r** [comment]
Yes, it easy to implement that is why I've already opened PR for that some time ago - #83

**Comment by xleclercq** [comment]
Oh! Oops. Can you change the PR so that it points to the alpha branch?

**Comment by xleclercq** [comment]
You don't have to worry about the makefiles, I can regenerate those anyway.

**Comment by Kvaz1r** [comment]
I made repoint to alpha branch and fix conflicts( removed changes in GNUmakefile).

**Comment by xleclercq** [comment]
Merged into master branch: 17502b4327593631d9d200045540500b0283f878
